
### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NDMxMjY4NTAsInN1YiI6IjEifQ.Z02IRKCtTYpm1jzv-kO6op2Jjscm6_dIF1sqyon2DtE
@baseUrl = http://localhost:8080

POST {{baseUrl}}/events
Content-Type: application/json

{
	"description": "Evento de teste 5",
	"address": "Rua Teste, 123",
	"date": "2025-03-20",
	"userId": "1"
}

###

GET {{baseUrl}}/events/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/events
Content-Type: application/json
Authorization: Bearer {{token}}
