POST http://localhost:8080/users
Content-Type: application/json

{
	"name": "John Doe",
	"email": "john.doe@example.com",
	"password": "password123"
}

###

POST http://localhost:8080/sign-in
Content-Type: application/json

{
	"email": "john.doe@example.com",
	"password": "password123"
}
